name: update

on:
  schedule:
    - cron: "0 2 * * *"

jobs:
  update:
    name: update
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12
        with:
          install_url: https://github.com/numtide/nix-flakes-installer/releases/latest/download/install
          nix_path: nixpkgs=channel:nixpkgs-unstable
          extra_nix_config: experimental-features = flakes nix-command

      - name: Set up cachix
        uses: cachix/cachix-action@v9
        with:
          name: nix-community
          signingKey: ${{ secrets.CACHIX_SIGNING_KEY }}

      - name: Update everything
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "action@github.com"

          nix-shell --run ./update -p "python3.withPackages (ps: [ ps.toml ])"
          if [ -n "$(git diff)" ]; then
            git commit -am "update toolchains"
          fi

          nix flake update --{recreate,commit}-lock-file

          curl -fLSso lib/rust-analyzer-vsix.zip \
            https://github.com/rust-analyzer/rust-analyzer/releases/download/nightly/rust-analyzer.vsix || true
          if [ -n "$(git diff)" ]; then
            git commit -am "update rust analyzer vscode extension"
          fi

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ github.token }}
          branch: main

      - name: Build with nix
        run: |
          pkgs=(.#{{minimal,default,complete,latest}.toolchain,rust-analyzer{,-vscode-extension}})
          nix build "${pkgs[@]}"
          nix build --no-write-lock-file --override-input \
            nixpkgs github:nixos/nixpkgs/nixpkgs-unstable "${pkgs[@]}"
